version: 0.2

env:
  variables:
    IMAGE_TAG: latest
    REGION: eu-central-1
    ACCOUNT_ID: 615215386069

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com)

  build:
    commands:
      - echo Building garmin_data_exporter image...
      - docker build -t garmin_data_exporter ./garmin_data_exporter
      - docker tag garmin_data_exporter $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/garmin_data_exporter:$IMAGE_TAG

      - echo Building grafana image...
      - docker build -t grafana ./grafana
      - docker tag grafana $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/grafana:$IMAGE_TAG

      - echo Building influxdb image...
      - docker build -t influxdb ./influxdb
      - docker tag influxdb $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/influxdb:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing images to ECR...
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/garmin_data_exporter:$IMAGE_TAG
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/grafana:$IMAGE_TAG
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/influxdb:$IMAGE_TAG

artifacts:
  files: '**/*'
